# Generated by Django 4.1.7 on 2026-02-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
