# Generated by Django 4.1.7 on 2024-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='invited_friends',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
