# Generated by Django 4.1.7 on 2024-06-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_note_content_alter_note_invited_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
