# Generated by Django 4.1.7 on 2024-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_note_content_alter_note_invited_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='note',
            name='invited_friends',
            field=models.JSONField(default=dict),
        ),
    ]
