# Generated by Django 4.1.7 on 2024-10-15 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0009_alter_note_content_alter_note_invited_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_added',
            new_name='edited',
        ),
        migrations.RemoveField(
            model_name='note',
            name='invited_friends',
        ),
        migrations.CreateModel(
            name='InvitedToNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invited_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.note')),
            ],
            options={
                'verbose_name': 'Invited to note',
                'verbose_name_plural': 'Invited to note',
            },
        ),
    ]
