# Generated by Django 4.1.7 on 2025-01-27 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_rename_date_added_note_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='edited',
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
