# Generated by Django 4.1.7 on 2023-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_text', models.TextField(default='dark')),
                ('chapter_color', models.TextField(default='#FFFFFF')),
                ('content_text', models.TextField(default='dark')),
                ('content_color', models.TextField(default='#FFFFFF')),
                ('menu_text', models.TextField(default='dark')),
                ('menu_color', models.TextField(default='#FFFFFF')),
                ('alg_text', models.TextField(default='dark')),
                ('alg_color', models.TextField(default='#FFFFFF')),
            ],
            options={
                'verbose_name': 'Colors',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='DescribeApp',
            fields=[
                ('id_app', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.TextField(default='')),
                ('app_describe', models.TextField(default='')),
                ('app_link', models.TextField(default='')),
                ('app_photo', models.ImageField(upload_to='homepage/')),
            ],
            options={
                'verbose_name': 'Describe App',
                'verbose_name_plural': 'Describe App',
            },
        ),
    ]
