# Generated by Django 4.1.7 on 2024-02-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubikcube', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescribeApp',
        ),
    ]
