# Generated by Django 4.1.7 on 2024-06-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nbp_api',
            options={'verbose_name': 'NBP API', 'verbose_name_plural': 'NBP API'},
        ),
    ]
