# Generated by Django 4.2.1 on 2023-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedtoeventmodel',
            name='accepted_invitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitedtoeventmodel',
            name='decline_invitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date_day',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
