# Generated by Django 4.1.7 on 2023-05-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_apps', '0002_alter_invitedtoeventmodel_accepted_invitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decription', models.CharField(default='wydatek', max_length=15)),
                ('price', models.FloatField(default=0.0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddExpenseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_title', models.CharField(default='', max_length=25)),
                ('status', models.CharField(default='brak wydatków', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddFriendToExpenseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_apps.addexpensegroup')),
                ('invited_to_group_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddFriendToExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_apps.addexpense')),
                ('invited_to_expense_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_apps.addexpensegroup'),
        ),
    ]
