# Generated by Django 4.1.7 on 2023-05-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0004_rename_expense_addexpense_expense_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfriendtoexpensegroup',
            old_name='expense',
            new_name='expeexpense_group_id',
        ),
    ]
