# Generated by Django 4.1.7 on 2023-05-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0005_rename_expense_addfriendtoexpensegroup_expeexpense_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfriendtoexpensegroup',
            old_name='expeexpense_group_id',
            new_name='expense_group_id',
        ),
    ]
