# Generated by Django 4.1.7 on 2023-05-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0006_rename_expeexpense_group_id_addfriendtoexpensegroup_expense_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfriendtoexpense',
            name='to_repayment',
            field=models.FloatField(default=0),
        ),
    ]
