# Generated by Django 4.1.7 on 2023-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0007_addfriendtoexpense_to_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpensegroup',
            name='status',
            field=models.CharField(default='Brak wydatków', max_length=15),
        ),
    ]
