# Generated by Django 4.1.7 on 2023-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0008_alter_addexpensegroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpense',
            name='repaid',
            field=models.FloatField(default=0.0),
        ),
    ]
