# Generated by Django 4.1.7 on 2023-05-27 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0012_alter_addfriendtoexpense_expense_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpense',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
