# Generated by Django 4.1.7 on 2023-05-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0014_alter_addexpensegroup_expense_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addexpense',
            old_name='decription',
            new_name='description',
        ),
    ]
