# Generated by Django 4.1.7 on 2023-05-30 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0015_rename_decription_addexpense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 8, 17, 50, 937592)),
        ),
        migrations.AlterField(
            model_name='addexpensegroup',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 8, 17, 50, 937592)),
        ),
    ]
