# Generated by Django 4.2.1 on 2023-09-19 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0019_openregistration_describe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateTimeField(default='2023-09-19 07:16'),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 7, 16, 15, 843149)),
        ),
        migrations.AlterField(
            model_name='addexpensegroup',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 7, 16, 15, 842149)),
        ),
    ]
