# Generated by Django 4.2.1 on 2023-12-15 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0021_availableapp_alter_addexpense_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 18, 7, 46, 621742)),
        ),
        migrations.AlterField(
            model_name='addexpensegroup',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 18, 7, 46, 620741)),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateTimeField(default='2023-12-15 18:07'),
        ),
        migrations.CreateModel(
            name='AppPhotos',
            fields=[
                ('id_photo', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='D:\\Rozne\\Kody\\6. Projekty WWW\\static/homepage/')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_apps.availableapp')),
            ],
        ),
    ]
