# Generated by Django 4.1.7 on 2023-12-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0046_beerstyles_alter_neweventmodel_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neweventmodel',
            name='event_date',
        ),
    ]
