# Generated by Django 4.1.7 on 2023-12-22 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0047_remove_neweventmodel_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 18, 35, 33, 745406, tzinfo=datetime.timezone.utc)),
        ),
    ]
