# Generated by Django 4.1.7 on 2023-12-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0048_neweventmodel_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
