# Generated by Django 4.1.7 on 2024-01-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0049_alter_neweventmodel_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
