# Generated by Django 4.1.7 on 2024-01-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0050_alter_neweventmodel_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='neweventmodel',
            name='past_event',
            field=models.BooleanField(default=False),
        ),
    ]
