# Generated by Django 4.1.7 on 2024-01-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0051_neweventmodel_past_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neweventmodel',
            name='past_event',
        ),
    ]
