# Generated by Django 4.1.7 on 2024-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0052_remove_neweventmodel_past_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableapp',
            name='app_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
