# Generated by Django 4.1.7 on 2024-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0053_availableapp_app_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neweventmodel',
            name='event_date_day',
        ),
        migrations.RemoveField(
            model_name='neweventmodel',
            name='event_date_month',
        ),
        migrations.RemoveField(
            model_name='neweventmodel',
            name='event_date_year',
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='openregistration',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
