# Generated by Django 4.1.7 on 2024-04-27 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0054_remove_neweventmodel_event_date_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neweventmodel',
            name='event_time',
            field=models.TimeField(default=datetime.time(20, 27, 41, 432395)),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateField(default=datetime.date(2024, 4, 27)),
        ),
    ]
