# Generated by Django 4.1.7 on 2024-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0055_neweventmodel_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_time',
            field=models.TimeField(),
        ),
    ]
