# Generated by Django 4.1.7 on 2024-04-28 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_apps', '0056_alter_neweventmodel_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neweventmodel',
            name='event_time',
        ),
        migrations.AddField(
            model_name='neweventmodel',
            name='event_date_day',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='neweventmodel',
            name='event_date_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='neweventmodel',
            name='event_date_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='neweventmodel',
            name='event_location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='NewEventModelNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='', max_length=20)),
                ('event_location', models.CharField(blank=True, default='', max_length=20)),
                ('event_description', models.CharField(blank=True, default='', max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
