# Generated by Django 4.1.7 on 2024-04-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0057_remove_neweventmodel_event_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neweventmodelnew',
            options={'verbose_name_plural': 'EventsNew'},
        ),
    ]
