# Generated by Django 4.1.7 on 2024-04-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0058_alter_neweventmodelnew_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neweventmodel',
            options={'verbose_name_plural': 'EventsOld'},
        ),
    ]
