# Generated by Django 4.1.7 on 2024-04-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0059_alter_neweventmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedtoeventmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_apps.neweventmodelnew'),
        ),
    ]
