# Generated by Django 4.1.7 on 2024-04-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0061_alter_invitedtoeventmodel_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neweventmodel',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='invitedtoeventmodelnew',
            options={'verbose_name': 'Invitations to events', 'verbose_name_plural': 'Invitations to events'},
        ),
        migrations.AlterModelOptions(
            name='neweventmodelnew',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.DeleteModel(
            name='InvitedToEventModel',
        ),
        migrations.DeleteModel(
            name='NewEventModel',
        ),
    ]
