# Generated by Django 4.1.7 on 2025-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0062_remove_neweventmodel_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neweventmodelnew',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='neweventmodelnew',
            name='event_title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
