# Generated by Django 4.1.7 on 2023-12-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flac_mp3_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='describeapp',
            name='video_link',
            field=models.TextField(default=''),
        ),
    ]
