# Generated by Django 4.1.7 on 2024-02-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flac_mp3_tag', '0002_describeapp_video_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescribeApp',
        ),
    ]
