# Generated by Django 4.1.7 on 2024-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flac_mp3_tag', '0003_delete_describeapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_link', models.TextField()),
            ],
        ),
    ]
