# Generated by Django 4.1.7 on 2025-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerStyles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.TextField(default='')),
                ('max_carbonation', models.FloatField(default=0)),
                ('min_carbonation', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Beer style',
                'verbose_name_plural': 'Beer styles',
            },
        ),
    ]
