# Generated by Django 4.1.7 on 2025-01-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonIcon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='beer_calc_icon/')),
            ],
            options={
                'verbose_name': 'Button Icon',
                'verbose_name_plural': 'Button Icon',
            },
        ),
    ]
