# Generated by Django 4.1.7 on 2024-12-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitthebills',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
