# Generated by Django 4.1.7 on 2024-12-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bills', '0002_splitthebills_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splitthebills',
            options={'verbose_name': 'Split the bills', 'verbose_name_plural': 'Split the bills'},
        ),
    ]
