# Generated by Django 4.1.7 on 2024-12-26 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split_the_bills', '0003_alter_splitthebills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split_the_bills.splitthebills')),
            ],
            options={
                'verbose_name': 'Add to group',
                'verbose_name_plural': 'Add to group',
            },
        ),
    ]
