# Generated by Django 4.1.7 on 2024-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bills', '0005_alter_splitthebills_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitthebills',
            name='bills',
            field=models.JSONField(default=dict),
        ),
    ]
