# Generated by Django 4.1.7 on 2024-12-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bills', '0006_alter_splitthebills_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitthebills',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
